### ISSUE TITLE
First-time run of /announcements doesn't seem to work correctly with long-term (greyed out?) modules 

### ISSUE THREAD

**Issue by frizensami** [indocomsoft/NUSIVLEBot#16]
My current module list looks like this:

![current-mods](https://user-images.githubusercontent.com/5507069/35778503-de50753c-09f9-11e8-99d1-29835f5a3096.png)

But when i run /annoucements for the first time I got:
![screenshot from 2018-02-04 22-22-49](https://user-images.githubusercontent.com/5507069/35778514-0bee7052-09fa-11e8-8884-65354d4ac9f6.png)

However, subsequent announcements are ok:
![correct-ann](https://user-images.githubusercontent.com/5507069/35778516-214d97ca-09fa-11e8-9408-93c1a4ccf34e.png)

User details: @frizensami on Telegram, name is Sriram Sami

**Comment by frizensami** [comment]
Minimum possible reproduction of problem:

1. /delete
2. /mods
3, /setup
4. Copy and paste token and hit enter
5. /push on
6. /announcements (this is the problematic one)
7. /announcements (this one is ok)

**Comment by indocomsoft** [comment]
Duplicate of #12

**Comment by frizensami** [comment]
Issue resolved in latest commit - first call of /announcements shows all modules. Thanks!
